# Project information
site_name: LamdaFeedback Documentation
site_author: Pierre Tharreau, Louis Manestar
site_description: >-
  Architecture, syntax and usage details for an online learning platform
  focused on providing rich feedback to the user.

# Page Tree
nav:
  - Home: index.md

  - Introduction:
      - "intro/index.md"
      - Contacts: "intro/contacts.md"
      - Terminology: "intro/terminology.md"

  - Students:
      - "student/index.md"

  - Teachers:
      - "teacher/index.md"
      - Guides:
          - Getting Started: "teacher/guides/gettingstarted.md"
          - Content Creation: "teacher/guides/content.md"
          - Analytics: "teacher/guides/analytics.md"
          - FAQ: "teacher/guides/faq.md"

      - Reference:
          - Response Areas:
              - "teacher/reference/response_area_components/index.md"
              - Text: "teacher/reference/response_area_components/Text.md"
              - Number: "teacher/reference/response_area_components/Number.md"
              - Boolean: "teacher/reference/response_area_components/Boolean.md"
              - NumericUnits: "teacher/reference/response_area_components/NumericUnits.md"
              - Expression: "teacher/reference/response_area_components/Expression.md"
              - MultipleChoice: "teacher/reference/response_area_components/MultipleChoice.md"
              - Matrix: "teacher/reference/response_area_components/Matrix.md"
              - Table: "teacher/reference/response_area_components/Table.md"

          - Evaluation Functions:
              - "teacher/reference/evaluation_functions/index.md"

  - Developers:
      - "developer/index.md"
      - Evaluation Functions:
          - Quickstart Guide: "developer/evaluation_functions/quickstart.md"
          - General Specification: "developer/evaluation_functions/specification.md"
          - Testing Functions Locally: "developer/evaluation_functions/local.md"
          - Evaluation Function Utils: "developer/evaluation_functions/module.md"
          - Deployed Functions:
              - "developer/evaluation_functions/index.md"
      - Response Area Components:
          - Creation Guide: "developer/placeholder.md"
          - Specification: "developer/placeholder.md"

# Configuration
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    # - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/eye-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/eye
        name: Switch to light mode

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - meta

# Plugins
plugins:
  - search
  - macros
  - evaldocsloader:
      functions_announce_endpoint: "https://staging-alpha-api.lambdafeedback.com/evaluation-functions/registered"
      api_key: !ENV [API_KEY, "disable"]
      add_to_section:
        ["Developers", "Evaluation Functions", "Deployed Functions"]

# Extra variables, accessible within markdown pages
extra:
  urls:
    client: https://alpha.lambdafeedback.com
